### PR TITLE
Covid-19 global rates WebApp

### PR DESCRIPTION
**Pull request by AndreaM2429**
Hello, this is a PR to review the full site of my React capstone project. The main goals for this project are:

## 🎯 **Milestones:**

📌 Fetch numeric data from an [disease.sh](https://disease.sh) API.
📌 Create a home page that has to allow the user to filter the data from a country name.
📌 Create a page for the details of the filter information (`CountriesDetail`).
📌 Follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), (Colors (blue), Typography (font face, size, and weight), Layout (composition and space between elements).
📌 Create test using Jest and React test library
📌 The project is a single-page application (SPA) built with React and Redux.
📌 Every page should have a unique route within the SPA.
📌 Deployed using [Render](https://render.com/), [Netlify](https://www.netlify.com/) or [GitHub Pages](https://pages.github.com/).
📌 Record a video presentation

### 🎖 General requirements:

- No linter errors.
- Documented the work

Thanks for the time to review my project, I appreciate that, and also thanks in advance for any feedback.

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @AndreaM2429 👋🏼👋🏼👋🏼👋🏼, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅✅

- [x] Descriptive commit messages👍🏼.
- [x] Functional and integration tests has been written as required and they are all passing👍🏼.
- [x] The application is a SPA, made possible by react router👍🏼.
- [x] Nice job sticking to the design👍🏼.
- [x] The back button has been implemented to route the user to the previous page👍🏼.
- [x] Nice job implementing an input search filter as this improves the UX of the app👍🏼.


## Required Changes ♻️

- [ ] Nice Job so far, everything about your project looks great including your video which looks very professional😉. But there's just one thing you might have forgotten to consider in your video😉. You didn't talk about a piece of code or a feature of the project that you have implemented and you are proud of😉. Please do well to talk about it as this is a requirement for the video presentation👍🏼.
image


_Check the comments under the review._

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AndreaM2429** [comment]
Hi @Ibizugbe, thanks for the time to review my project.
I would like to clarify that I talk about a piece of code at the end of the video, maybe I don't say it in that way but I did it.

**Comment by Ibizugbe** [comment]
> Hi @Ibizugbe, thanks for the time to review my project. I would like to clarify that I talk about a piece of code at the end of the video, maybe I don't say it in that way but I did it.

Hi @AndreaM2429 👋🏼👋🏼, Yeahh, I noticed you presented some code and this was a difficult decision for Me, this is because it was difficult to differentiate whether this was the piece of code you are proud of or it was just a general walk through your code base. I am sorry about any inconviniences, but you can just do well to implement the change as required👍🏼.

**Review by DammyShittu — APPROVED** [review]
Hi @AndreaM2429,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
